---
- hosts: 172.31.29.229
  become: True
  tasks:
    - name: Install Apache Server
      yum:
        name: httpd
        state: present
    - name: Enable Apache on Reboot
      service:
        name: httpd
        enabled: True
    - name: Install Git
      yum:
        name: git
        state: present
    - name: Deploy Website from GitHub
      git:
        repo: https://github.com/nareshbandapally916/javahome-app
        dest: /var/www/html/
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
...

